import WeeklyView from "./weeklyView/WeeklyView";
import ViewFeed from "./viewFeed/ViewFeed";
import ViewRegion from "./viewRegion/ViewRegion";
import MyInfo from "./myInfo/MyInfo";
import AroundMe from "./aroundMe/AroundMe";
import Login from "./admin/Login";
import RegisterClimingGround from "./admin/RegisterClimingGround";
import RegisterFeed from "./admin/RegisterFeed";
import AdminViewFeedCard from "./admin/AdminViewFeedCard";
import AdminViewFeed from "./admin/AdminViewFeed";
export { WeeklyView, ViewFeed, ViewRegion, MyInfo, AroundMe, Login, RegisterClimingGround, RegisterFeed, AdminViewFeed, AdminViewFeedCard };
